/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as BottomsRouteImport } from './routes/bottoms'
import { Route as DressesRouteImport } from './routes/dresses'
import { Route as KnitwearRouteImport } from './routes/knitwear'
import { Route as OuterwearRouteImport } from './routes/outerwear'
import { Route as OutfitsRouteImport } from './routes/outfits'
import { Route as TopsRouteImport } from './routes/tops'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const BottomsRoute = BottomsRouteImport.update({
  id: '/bottoms',
  path: '/bottoms',
  getParentRoute: () => rootRouteImport,
} as any)
const DressesRoute = DressesRouteImport.update({
  id: '/dresses',
  path: '/dresses',
  getParentRoute: () => rootRouteImport,
} as any)
const KnitwearRoute = KnitwearRouteImport.update({
  id: '/knitwear',
  path: '/knitwear',
  getParentRoute: () => rootRouteImport,
} as any)
const OuterwearRoute = OuterwearRouteImport.update({
  id: '/outerwear',
  path: '/outerwear',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitsRoute = OutfitsRouteImport.update({
  id: '/outfits',
  path: '/outfits',
  getParentRoute: () => rootRouteImport,
} as any)
const TopsRoute = TopsRouteImport.update({
  id: '/tops',
  path: '/tops',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/bottoms': typeof BottomsRoute
  '/dresses': typeof DressesRoute
  '/knitwear': typeof KnitwearRoute
  '/outerwear': typeof OuterwearRoute
  '/outfits': typeof OutfitsRoute
  '/tops': typeof TopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/bottoms': typeof BottomsRoute
  '/dresses': typeof DressesRoute
  '/knitwear': typeof KnitwearRoute
  '/outerwear': typeof OuterwearRoute
  '/outfits': typeof OutfitsRoute
  '/tops': typeof TopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/bottoms': typeof BottomsRoute
  '/dresses': typeof DressesRoute
  '/knitwear': typeof KnitwearRoute
  '/outerwear': typeof OuterwearRoute
  '/outfits': typeof OutfitsRoute
  '/tops': typeof TopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/bottoms'
    | '/dresses'
    | '/knitwear'
    | '/outerwear'
    | '/outfits'
    | '/tops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/bottoms'
    | '/dresses'
    | '/knitwear'
    | '/outerwear'
    | '/outfits'
    | '/tops'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/bottoms'
    | '/dresses'
    | '/knitwear'
    | '/outerwear'
    | '/outfits'
    | '/tops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  BottomsRoute: typeof BottomsRoute
  DressesRoute: typeof DressesRoute
  KnitwearRoute: typeof KnitwearRoute
  OuterwearRoute: typeof OuterwearRoute
  OutfitsRoute: typeof OutfitsRoute
  TopsRoute: typeof TopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bottoms': {
      id: '/bottoms'
      path: '/bottoms'
      fullPath: '/bottoms'
      preLoaderRoute: typeof BottomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dresses': {
      id: '/dresses'
      path: '/dresses'
      fullPath: '/dresses'
      preLoaderRoute: typeof DressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knitwear': {
      id: '/knitwear'
      path: '/knitwear'
      fullPath: '/knitwear'
      preLoaderRoute: typeof KnitwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outerwear': {
      id: '/outerwear'
      path: '/outerwear'
      fullPath: '/outerwear'
      preLoaderRoute: typeof OuterwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfits': {
      id: '/outfits'
      path: '/outfits'
      fullPath: '/outfits'
      preLoaderRoute: typeof OutfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tops': {
      id: '/tops'
      path: '/tops'
      fullPath: '/tops'
      preLoaderRoute: typeof TopsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  BottomsRoute: BottomsRoute,
  DressesRoute: DressesRoute,
  KnitwearRoute: KnitwearRoute,
  OuterwearRoute: OuterwearRoute,
  OutfitsRoute: OutfitsRoute,
  TopsRoute: TopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
